# Generated by Django 3.1.5 on 2021-01-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=100)),
                ('micron', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('texture', models.CharField(max_length=100)),
            ],
        ),
    ]
